diff --git a/Makefile b/Makefile
index 1750898..f72cae4 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,3 @@
-LD_LIB_PATH=:./json-c-build
-JSON_C_LDFLAGS=./json-c-build/libjson-c.a
-JSON_C_CFLAGS=-I./json-c -I./json-c-build
-JSON_C_RULE=./json-c-build/libjson-c.a
 API_RULE_DEPEDENCIES=
 OAPI_APPIMAGE_RULE_DEPEDENCIES=
 APPIMAGETOOL_OPTION=
@@ -12,15 +8,6 @@ include COGNAC/oapi-cli.mk
 COGNAC/oapi-cli.mk:
 	git submodule update --init

-json-c/.git:
-	git clone https://github.com/cosmo-ray/json-c.git -b color
-
-json-c-build/libjson-c.a: json-c/.git
-	rm -rvf ./json-c-build
-	mkdir json-c-build
-	cd json-c-build && cmake ../json-c "$${CMAKE_ARG}" # might need to be replace by cmake3
-	make -C json-c-build json-c-static
-
 main-helper.h:
 	cp  COGNAC/main-helper.h .
